package com.cos.model.base;

public class BasicExample {
 
    protected Integer firstResult;
	
	protected Integer maxResults;
	
	protected String direct;
   
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    public void clear() {
		firstResult=null;
		maxResults=null;
		direct=null;
	}

	public Integer getFirstResult() {
		return firstResult;
	}

	public void setFirstResult(Integer firstResult) {
		this.firstResult = firstResult;
	}

	public Integer getMaxResults() {
		return maxResults;
	}

	public void setMaxResults(Integer maxResults) {
		this.maxResults = maxResults;
	}

	public String getDirect() {
		return direct;
	}

	public void setDirect(String direct) {
		this.direct = direct;
	}
    
}