package com.cos.model;

import java.util.Date;

public class FansGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans_group.id_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans_group.name_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans_group.desc_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans_group.type_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans_group.create_by_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans_group.create_time_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_group.id_
     *
     * @return the value of fans_group.id_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_group.id_
     *
     * @param id the value for fans_group.id_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_group.name_
     *
     * @return the value of fans_group.name_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_group.name_
     *
     * @param name the value for fans_group.name_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_group.desc_
     *
     * @return the value of fans_group.desc_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_group.desc_
     *
     * @param desc the value for fans_group.desc_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_group.type_
     *
     * @return the value of fans_group.type_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_group.type_
     *
     * @param type the value for fans_group.type_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_group.create_by_
     *
     * @return the value of fans_group.create_by_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_group.create_by_
     *
     * @param createBy the value for fans_group.create_by_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans_group.create_time_
     *
     * @return the value of fans_group.create_time_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans_group.create_time_
     *
     * @param createTime the value for fans_group.create_time_
     *
     * @mbg.generated Sat Jun 03 16:14:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}