package com.cos.model;

public class ProvinceCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.id_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.area_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private Integer areaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.p_area_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private Integer pAreaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.area_name_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.province_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private String provinceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.city_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private String cityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.zip_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private String zipCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province_code.devision_level_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	private Integer devisionLevel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.id_
	 * @return  the value of province_code.id_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.id_
	 * @param id  the value for province_code.id_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.area_code_
	 * @return  the value of province_code.area_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public Integer getAreaCode() {
		return areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.area_code_
	 * @param areaCode  the value for province_code.area_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setAreaCode(Integer areaCode) {
		this.areaCode = areaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.p_area_code_
	 * @return  the value of province_code.p_area_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public Integer getpAreaCode() {
		return pAreaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.p_area_code_
	 * @param pAreaCode  the value for province_code.p_area_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setpAreaCode(Integer pAreaCode) {
		this.pAreaCode = pAreaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.area_name_
	 * @return  the value of province_code.area_name_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.area_name_
	 * @param areaName  the value for province_code.area_name_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName == null ? null : areaName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.province_code_
	 * @return  the value of province_code.province_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public String getProvinceCode() {
		return provinceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.province_code_
	 * @param provinceCode  the value for province_code.province_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode == null ? null : provinceCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.city_code_
	 * @return  the value of province_code.city_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public String getCityCode() {
		return cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.city_code_
	 * @param cityCode  the value for province_code.city_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode == null ? null : cityCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.zip_code_
	 * @return  the value of province_code.zip_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.zip_code_
	 * @param zipCode  the value for province_code.zip_code_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode == null ? null : zipCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province_code.devision_level_
	 * @return  the value of province_code.devision_level_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public Integer getDevisionLevel() {
		return devisionLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province_code.devision_level_
	 * @param devisionLevel  the value for province_code.devision_level_
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	public void setDevisionLevel(Integer devisionLevel) {
		this.devisionLevel = devisionLevel;
	}
}