package com.cos.model;

import java.util.Date;

import com.cos.common.utils.DateTimeUtil;

public class Reply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.id_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.content_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.comment_id_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private Long commentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.reply_to_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private String replyTo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.curr_version_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private Short currVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.tocken_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private String tocken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.create_by_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.create_time_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	private Date createTime;
	
 
	
	private SysAccount author;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.id_
	 * @return  the value of reply.id_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public Long getId() {
		return id;
	}
    
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.id_
	 * @param id  the value for reply.id_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.content_
	 * @return  the value of reply.content_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.content_
	 * @param content  the value for reply.content_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.comment_id_
	 * @return  the value of reply.comment_id_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public Long getCommentId() {
		return commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.comment_id_
	 * @param commentId  the value for reply.comment_id_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.reply_to_
	 * @return  the value of reply.reply_to_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public String getReplyTo() {
		return replyTo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.reply_to_
	 * @param replyTo  the value for reply.reply_to_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setReplyTo(String replyTo) {
		this.replyTo = replyTo == null ? null : replyTo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.curr_version_
	 * @return  the value of reply.curr_version_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public Short getCurrVersion() {
		return currVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.curr_version_
	 * @param currVersion  the value for reply.curr_version_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setCurrVersion(Short currVersion) {
		this.currVersion = currVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.tocken_
	 * @return  the value of reply.tocken_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public String getTocken() {
		return tocken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.tocken_
	 * @param tocken  the value for reply.tocken_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setTocken(String tocken) {
		this.tocken = tocken == null ? null : tocken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.create_by_
	 * @return  the value of reply.create_by_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.create_by_
	 * @param createBy  the value for reply.create_by_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.create_time_
	 * @return  the value of reply.create_time_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.create_time_
	 * @param createTime  the value for reply.create_time_
	 * @mbg.generated  Wed Aug 23 16:53:50 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public SysAccount getAuthor() {
		return author;
	}

	public void setAuthor(SysAccount author) {
		this.author = author;
	}
	
	public String getDayNumFromCurrentDay(){
		return DateTimeUtil.getDayNumFromCurrentDay(this.createTime);
	}
}