package com.cos.model;


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.cos.model.base.BasicExample;

public class BaseDictionaryitemExample  extends BasicExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public BaseDictionaryitemExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}
	
	 
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;
		protected List<Criterion> fieldsCriteria;
		
		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
			fieldsCriteria=new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getFieldsCriteria() {
			return fieldsCriteria;
		}
        
		public List<Criterion> getCriteria() {
			return criteria;
		}
		
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addFieldsCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			fieldsCriteria.add(new Criterion(condition));
		}
		
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		public Criteria getIdCaption() {
			addFieldsCriterion("id_");
			return (Criteria) this;
		}
		
		public Criteria andIdIsNull() {
			addCriterion("id_ is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id_ is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id_ =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id_ <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id_ >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id_ >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id_ <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id_ <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id_ in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id_ not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id_ between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id_ not between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria getDictCodeCaption(){
			addFieldsCriterion("dict_code_");
			return (Criteria) this;
		}
		
		public Criteria andDictCodeIsNull() {
			addCriterion("dict_code_ is null");
			return (Criteria) this;
		}

		public Criteria andDictCodeIsNotNull() {
			addCriterion("dict_code_ is not null");
			return (Criteria) this;
		}

		public Criteria andDictCodeEqualTo(String value) {
			addCriterion("dict_code_ =", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeNotEqualTo(String value) {
			addCriterion("dict_code_ <>", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeGreaterThan(String value) {
			addCriterion("dict_code_ >", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeGreaterThanOrEqualTo(String value) {
			addCriterion("dict_code_ >=", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeLessThan(String value) {
			addCriterion("dict_code_ <", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeLessThanOrEqualTo(String value) {
			addCriterion("dict_code_ <=", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeLike(String value) {
			addCriterion("dict_code_ like", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeNotLike(String value) {
			addCriterion("dict_code_ not like", value, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeIn(List<String> values) {
			addCriterion("dict_code_ in", values, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeNotIn(List<String> values) {
			addCriterion("dict_code_ not in", values, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeBetween(String value1, String value2) {
			addCriterion("dict_code_ between", value1, value2, "dictCode");
			return (Criteria) this;
		}

		public Criteria andDictCodeNotBetween(String value1, String value2) {
			addCriterion("dict_code_ not between", value1, value2, "dictCode");
			return (Criteria) this;
		}
		
		public Criteria getDictitemNameCaption(){
			addFieldsCriterion("dictitem_name_");
			return (Criteria) this;
		}
		
		public Criteria andDictitemNameIsNull() {
			addCriterion("dictitem_name_ is null");
			return (Criteria) this;
		}

		public Criteria andDictitemNameIsNotNull() {
			addCriterion("dictitem_name_ is not null");
			return (Criteria) this;
		}

		public Criteria andDictitemNameEqualTo(String value) {
			addCriterion("dictitem_name_ =", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameNotEqualTo(String value) {
			addCriterion("dictitem_name_ <>", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameGreaterThan(String value) {
			addCriterion("dictitem_name_ >", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameGreaterThanOrEqualTo(String value) {
			addCriterion("dictitem_name_ >=", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameLessThan(String value) {
			addCriterion("dictitem_name_ <", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameLessThanOrEqualTo(String value) {
			addCriterion("dictitem_name_ <=", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameLike(String value) {
			addCriterion("dictitem_name_ like", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameNotLike(String value) {
			addCriterion("dictitem_name_ not like", value, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameIn(List<String> values) {
			addCriterion("dictitem_name_ in", values, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameNotIn(List<String> values) {
			addCriterion("dictitem_name_ not in", values, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameBetween(String value1, String value2) {
			addCriterion("dictitem_name_ between", value1, value2, "dictitemName");
			return (Criteria) this;
		}

		public Criteria andDictitemNameNotBetween(String value1, String value2) {
			addCriterion("dictitem_name_ not between", value1, value2, "dictitemName");
			return (Criteria) this;
		}

		public Criteria getDictitemValueCaption(){
			addFieldsCriterion("dictitem_value_");
			return (Criteria) this;
		}
		
		public Criteria andDictitemValueIsNull() {
			addCriterion("dictitem_value_ is null");
			return (Criteria) this;
		}

		public Criteria andDictitemValueIsNotNull() {
			addCriterion("dictitem_value_ is not null");
			return (Criteria) this;
		}

		public Criteria andDictitemValueEqualTo(String value) {
			addCriterion("dictitem_value_ =", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueNotEqualTo(String value) {
			addCriterion("dictitem_value_ <>", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueGreaterThan(String value) {
			addCriterion("dictitem_value_ >", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueGreaterThanOrEqualTo(String value) {
			addCriterion("dictitem_value_ >=", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueLessThan(String value) {
			addCriterion("dictitem_value_ <", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueLessThanOrEqualTo(String value) {
			addCriterion("dictitem_value_ <=", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueLike(String value) {
			addCriterion("dictitem_value_ like", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueNotLike(String value) {
			addCriterion("dictitem_value_ not like", value, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueIn(List<String> values) {
			addCriterion("dictitem_value_ in", values, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueNotIn(List<String> values) {
			addCriterion("dictitem_value_ not in", values, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueBetween(String value1, String value2) {
			addCriterion("dictitem_value_ between", value1, value2, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria andDictitemValueNotBetween(String value1, String value2) {
			addCriterion("dictitem_value_ not between", value1, value2, "dictitemValue");
			return (Criteria) this;
		}

		public Criteria getDictitemDescCaption(){
			addFieldsCriterion("dictitem_desc_");
			return (Criteria) this;
		}
		
		public Criteria andDictitemDescIsNull() {
			addCriterion("dictitem_desc_ is null");
			return (Criteria) this;
		}

		public Criteria andDictitemDescIsNotNull() {
			addCriterion("dictitem_desc_ is not null");
			return (Criteria) this;
		}

		public Criteria andDictitemDescEqualTo(String value) {
			addCriterion("dictitem_desc_ =", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescNotEqualTo(String value) {
			addCriterion("dictitem_desc_ <>", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescGreaterThan(String value) {
			addCriterion("dictitem_desc_ >", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescGreaterThanOrEqualTo(String value) {
			addCriterion("dictitem_desc_ >=", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescLessThan(String value) {
			addCriterion("dictitem_desc_ <", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescLessThanOrEqualTo(String value) {
			addCriterion("dictitem_desc_ <=", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescLike(String value) {
			addCriterion("dictitem_desc_ like", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescNotLike(String value) {
			addCriterion("dictitem_desc_ not like", value, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescIn(List<String> values) {
			addCriterion("dictitem_desc_ in", values, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescNotIn(List<String> values) {
			addCriterion("dictitem_desc_ not in", values, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescBetween(String value1, String value2) {
			addCriterion("dictitem_desc_ between", value1, value2, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria andDictitemDescNotBetween(String value1, String value2) {
			addCriterion("dictitem_desc_ not between", value1, value2, "dictitemDesc");
			return (Criteria) this;
		}

		public Criteria getSortIdCaption(){
			addFieldsCriterion("sort_id_");
			return (Criteria) this;
		}
		
		public Criteria andSortIdIsNull() {
			addCriterion("sort_id_ is null");
			return (Criteria) this;
		}

		public Criteria andSortIdIsNotNull() {
			addCriterion("sort_id_ is not null");
			return (Criteria) this;
		}

		public Criteria andSortIdEqualTo(Integer value) {
			addCriterion("sort_id_ =", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdNotEqualTo(Integer value) {
			addCriterion("sort_id_ <>", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdGreaterThan(Integer value) {
			addCriterion("sort_id_ >", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("sort_id_ >=", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdLessThan(Integer value) {
			addCriterion("sort_id_ <", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdLessThanOrEqualTo(Integer value) {
			addCriterion("sort_id_ <=", value, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdIn(List<Integer> values) {
			addCriterion("sort_id_ in", values, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdNotIn(List<Integer> values) {
			addCriterion("sort_id_ not in", values, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdBetween(Integer value1, Integer value2) {
			addCriterion("sort_id_ between", value1, value2, "sortId");
			return (Criteria) this;
		}

		public Criteria andSortIdNotBetween(Integer value1, Integer value2) {
			addCriterion("sort_id_ not between", value1, value2, "sortId");
			return (Criteria) this;
		}
		
		
		
		public Criteria getCreatedByCaption() {
			addFieldsCriterion("created_by_");
			return (Criteria) this;
		}
		
		public Criteria andCreatedByIsNull() {
			addCriterion("created_by_ is null");
			return (Criteria) this;
		}

		public Criteria andCreatedByIsNotNull() {
			addCriterion("created_by_ is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedByEqualTo(Long value) {
			addCriterion("created_by_ =", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotEqualTo(Long value) {
			addCriterion("created_by_ <>", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThan(Long value) {
			addCriterion("created_by_ >", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
			addCriterion("created_by_ >=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThan(Long value) {
			addCriterion("created_by_ <", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByLessThanOrEqualTo(Long value) {
			addCriterion("created_by_ <=", value, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByIn(List<Long> values) {
			addCriterion("created_by_ in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotIn(List<Long> values) {
			addCriterion("created_by_ not in", values, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByBetween(Long value1, Long value2) {
			addCriterion("created_by_ between", value1, value2, "createdBy");
			return (Criteria) this;
		}

		public Criteria andCreatedByNotBetween(Long value1, Long value2) {
			addCriterion("created_by_ not between", value1, value2, "createdBy");
			return (Criteria) this;
		}
		
		public Criteria getCreatedTimeCaption() {
			addFieldsCriterion("created_time_");
			return (Criteria) this;
		}
		
		public Criteria andCreatedTimeIsNull() {
			addCriterion("created_time_ is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIsNotNull() {
			addCriterion("created_time_ is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeEqualTo(Date value) {
			addCriterion("created_time_ =", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotEqualTo(Date value) {
			addCriterion("created_time_ <>", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThan(Date value) {
			addCriterion("created_time_ >", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("created_time_ >=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThan(Date value) {
			addCriterion("created_time_ <", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
			addCriterion("created_time_ <=", value, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeIn(List<Date> values) {
			addCriterion("created_time_ in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotIn(List<Date> values) {
			addCriterion("created_time_ not in", values, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeBetween(Date value1, Date value2) {
			addCriterion("created_time_ between", value1, value2, "createdTime");
			return (Criteria) this;
		}

		public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
			addCriterion("created_time_ not between", value1, value2, "createdTime");
			return (Criteria) this;
		}

	
		
		public Criteria getStatusCaption() {
			addFieldsCriterion("status_");
			return (Criteria) this;
		}
		
		public Criteria andStatusIsNull() {
			addCriterion("status_ is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status_ is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status_ =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status_ <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status_ >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status_ >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status_ <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status_ <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status_ in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status_ not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status_ between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status_ not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria getCurrVersionCaption() {
			addFieldsCriterion("curr_version_");
			return (Criteria) this;
		}
		
		public Criteria andCurrVersionIsNull() {
			addCriterion("curr_version_ is null");
			return (Criteria) this;
		}

		public Criteria andCurrVersionIsNotNull() {
			addCriterion("curr_version_ is not null");
			return (Criteria) this;
		}

		public Criteria andCurrVersionEqualTo(Short value) {
			addCriterion("curr_version_ =", value, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionNotEqualTo(Short value) {
			addCriterion("curr_version_ <>", value, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionGreaterThan(Short value) {
			addCriterion("curr_version_ >", value, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionGreaterThanOrEqualTo(Short value) {
			addCriterion("curr_version_ >=", value, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionLessThan(Short value) {
			addCriterion("curr_version_ <", value, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionLessThanOrEqualTo(Short value) {
			addCriterion("curr_version_ <=", value, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionIn(List<Short> values) {
			addCriterion("curr_version_ in", values, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionNotIn(List<Short> values) {
			addCriterion("curr_version_ not in", values, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionBetween(Short value1, Short value2) {
			addCriterion("curr_version_ between", value1, value2, "currVersion");
			return (Criteria) this;
		}

		public Criteria andCurrVersionNotBetween(Short value1, Short value2) {
			addCriterion("curr_version_ not between", value1, value2, "currVersion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database service base_dictionaryitem
	 * @mbggenerated  Fri Aug 19 15:57:33 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database service base_dictionaryitem
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 09 17:15:38 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}