package com.cos.model;

import java.util.Date;

 

public class BaseDictionary{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.id_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.dict_code_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private String dictCode="";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.dict_name_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.dict_desc_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private String dictDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.created_by_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.created_time_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.last_updated_by_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private Long lastUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.last_updated_time_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private Date lastUpdatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.status_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dictionary.curr_version_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    private Short currVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.id_
     *
     * @return the value of base_dictionary.id_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.id_
     *
     * @param id the value for base_dictionary.id_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.dict_code_
     *
     * @return the value of base_dictionary.dict_code_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.dict_code_
     *
     * @param dictCode the value for base_dictionary.dict_code_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.dict_name_
     *
     * @return the value of base_dictionary.dict_name_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.dict_name_
     *
     * @param dictName the value for base_dictionary.dict_name_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.dict_desc_
     *
     * @return the value of base_dictionary.dict_desc_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.dict_desc_
     *
     * @param dictDesc the value for base_dictionary.dict_desc_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc == null ? null : dictDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.created_by_
     *
     * @return the value of base_dictionary.created_by_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.created_by_
     *
     * @param createdBy the value for base_dictionary.created_by_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.created_time_
     *
     * @return the value of base_dictionary.created_time_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.created_time_
     *
     * @param createdTime the value for base_dictionary.created_time_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.last_updated_by_
     *
     * @return the value of base_dictionary.last_updated_by_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.last_updated_by_
     *
     * @param lastUpdatedBy the value for base_dictionary.last_updated_by_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.last_updated_time_
     *
     * @return the value of base_dictionary.last_updated_time_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public Date getLastUpdatedTime() {
        return lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.last_updated_time_
     *
     * @param lastUpdatedTime the value for base_dictionary.last_updated_time_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setLastUpdatedTime(Date lastUpdatedTime) {
        this.lastUpdatedTime = lastUpdatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.status_
     *
     * @return the value of base_dictionary.status_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.status_
     *
     * @param status the value for base_dictionary.status_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dictionary.curr_version_
     *
     * @return the value of base_dictionary.curr_version_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public Short getCurrVersion() {
        return currVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dictionary.curr_version_
     *
     * @param currVersion the value for base_dictionary.curr_version_
     *
     * @mbggenerated Fri Sep 23 09:51:51 CST 2016
     */
    public void setCurrVersion(Short currVersion) {
        this.currVersion = currVersion;
    }
}