package com.cos.model;

import java.util.Date;

public class CollectFolder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_folder.id_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_folder.folder_type_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    private String folderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_folder.topic_id_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_folder.create_by_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_folder.create_time_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_folder.id_
     *
     * @return the value of collect_folder.id_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_folder.id_
     *
     * @param id the value for collect_folder.id_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_folder.folder_type_
     *
     * @return the value of collect_folder.folder_type_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public String getFolderType() {
        return folderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_folder.folder_type_
     *
     * @param folderType the value for collect_folder.folder_type_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public void setFolderType(String folderType) {
        this.folderType = folderType == null ? null : folderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_folder.topic_id_
     *
     * @return the value of collect_folder.topic_id_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_folder.topic_id_
     *
     * @param topicId the value for collect_folder.topic_id_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_folder.create_by_
     *
     * @return the value of collect_folder.create_by_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_folder.create_by_
     *
     * @param createBy the value for collect_folder.create_by_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_folder.create_time_
     *
     * @return the value of collect_folder.create_time_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_folder.create_time_
     *
     * @param createTime the value for collect_folder.create_time_
     *
     * @mbg.generated Thu May 18 16:43:50 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}