package com.cos.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.cos.model.base.BasicExample;

public class CommentExample  extends BasicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public CommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public void clear() {
    	super.clear();
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content_ is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content_ is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content_ =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content_ <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content_ >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content_ >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content_ <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content_ <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content_ like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content_ not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content_ in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content_ not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content_ between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content_ not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNull() {
            addCriterion("target_id_ is null");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNotNull() {
            addCriterion("target_id_ is not null");
            return (Criteria) this;
        }

        public Criteria andTargetIdEqualTo(Long value) {
            addCriterion("target_id_ =", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotEqualTo(Long value) {
            addCriterion("target_id_ <>", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThan(Long value) {
            addCriterion("target_id_ >", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThanOrEqualTo(Long value) {
            addCriterion("target_id_ >=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThan(Long value) {
            addCriterion("target_id_ <", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThanOrEqualTo(Long value) {
            addCriterion("target_id_ <=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIn(List<Long> values) {
            addCriterion("target_id_ in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotIn(List<Long> values) {
            addCriterion("target_id_ not in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdBetween(Long value1, Long value2) {
            addCriterion("target_id_ between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotBetween(Long value1, Long value2) {
            addCriterion("target_id_ not between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andReplyIdsIsNull() {
            addCriterion("reply_ids_ is null");
            return (Criteria) this;
        }

        public Criteria andReplyIdsIsNotNull() {
            addCriterion("reply_ids_ is not null");
            return (Criteria) this;
        }

        public Criteria andReplyIdsEqualTo(String value) {
            addCriterion("reply_ids_ =", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotEqualTo(String value) {
            addCriterion("reply_ids_ <>", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsGreaterThan(String value) {
            addCriterion("reply_ids_ >", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsGreaterThanOrEqualTo(String value) {
            addCriterion("reply_ids_ >=", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsLessThan(String value) {
            addCriterion("reply_ids_ <", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsLessThanOrEqualTo(String value) {
            addCriterion("reply_ids_ <=", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsLike(String value) {
            addCriterion("reply_ids_ like", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotLike(String value) {
            addCriterion("reply_ids_ not like", value, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsIn(List<String> values) {
            addCriterion("reply_ids_ in", values, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotIn(List<String> values) {
            addCriterion("reply_ids_ not in", values, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsBetween(String value1, String value2) {
            addCriterion("reply_ids_ between", value1, value2, "replyIds");
            return (Criteria) this;
        }

        public Criteria andReplyIdsNotBetween(String value1, String value2) {
            addCriterion("reply_ids_ not between", value1, value2, "replyIds");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade_ is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade_ is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("grade_ =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("grade_ <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("grade_ >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade_ >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("grade_ <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("grade_ <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("grade_ in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("grade_ not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("grade_ between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("grade_ not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andEndorseIsNull() {
            addCriterion("endorse_ is null");
            return (Criteria) this;
        }

        public Criteria andEndorseIsNotNull() {
            addCriterion("endorse_ is not null");
            return (Criteria) this;
        }

        public Criteria andEndorseEqualTo(Integer value) {
            addCriterion("endorse_ =", value, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseNotEqualTo(Integer value) {
            addCriterion("endorse_ <>", value, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseGreaterThan(Integer value) {
            addCriterion("endorse_ >", value, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseGreaterThanOrEqualTo(Integer value) {
            addCriterion("endorse_ >=", value, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseLessThan(Integer value) {
            addCriterion("endorse_ <", value, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseLessThanOrEqualTo(Integer value) {
            addCriterion("endorse_ <=", value, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseIn(List<Integer> values) {
            addCriterion("endorse_ in", values, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseNotIn(List<Integer> values) {
            addCriterion("endorse_ not in", values, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseBetween(Integer value1, Integer value2) {
            addCriterion("endorse_ between", value1, value2, "endorse");
            return (Criteria) this;
        }

        public Criteria andEndorseNotBetween(Integer value1, Integer value2) {
            addCriterion("endorse_ not between", value1, value2, "endorse");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status_ is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status_ is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status_ =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status_ <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status_ >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status_ >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status_ <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status_ <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status_ in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status_ not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status_ between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status_ not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTockenIsNull() {
            addCriterion("tocken_ is null");
            return (Criteria) this;
        }

        public Criteria andTockenIsNotNull() {
            addCriterion("tocken_ is not null");
            return (Criteria) this;
        }

        public Criteria andTockenEqualTo(String value) {
            addCriterion("tocken_ =", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenNotEqualTo(String value) {
            addCriterion("tocken_ <>", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenGreaterThan(String value) {
            addCriterion("tocken_ >", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenGreaterThanOrEqualTo(String value) {
            addCriterion("tocken_ >=", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenLessThan(String value) {
            addCriterion("tocken_ <", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenLessThanOrEqualTo(String value) {
            addCriterion("tocken_ <=", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenLike(String value) {
            addCriterion("tocken_ like", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenNotLike(String value) {
            addCriterion("tocken_ not like", value, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenIn(List<String> values) {
            addCriterion("tocken_ in", values, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenNotIn(List<String> values) {
            addCriterion("tocken_ not in", values, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenBetween(String value1, String value2) {
            addCriterion("tocken_ between", value1, value2, "tocken");
            return (Criteria) this;
        }

        public Criteria andTockenNotBetween(String value1, String value2) {
            addCriterion("tocken_ not between", value1, value2, "tocken");
            return (Criteria) this;
        }

        public Criteria andCurrVersionIsNull() {
            addCriterion("curr_version_ is null");
            return (Criteria) this;
        }

        public Criteria andCurrVersionIsNotNull() {
            addCriterion("curr_version_ is not null");
            return (Criteria) this;
        }

        public Criteria andCurrVersionEqualTo(Short value) {
            addCriterion("curr_version_ =", value, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionNotEqualTo(Short value) {
            addCriterion("curr_version_ <>", value, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionGreaterThan(Short value) {
            addCriterion("curr_version_ >", value, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionGreaterThanOrEqualTo(Short value) {
            addCriterion("curr_version_ >=", value, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionLessThan(Short value) {
            addCriterion("curr_version_ <", value, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionLessThanOrEqualTo(Short value) {
            addCriterion("curr_version_ <=", value, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionIn(List<Short> values) {
            addCriterion("curr_version_ in", values, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionNotIn(List<Short> values) {
            addCriterion("curr_version_ not in", values, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionBetween(Short value1, Short value2) {
            addCriterion("curr_version_ between", value1, value2, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCurrVersionNotBetween(Short value1, Short value2) {
            addCriterion("curr_version_ not between", value1, value2, "currVersion");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(Long value) {
            addCriterion("create_by_ =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(Long value) {
            addCriterion("create_by_ <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(Long value) {
            addCriterion("create_by_ >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(Long value) {
            addCriterion("create_by_ >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(Long value) {
            addCriterion("create_by_ <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(Long value) {
            addCriterion("create_by_ <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<Long> values) {
            addCriterion("create_by_ in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<Long> values) {
            addCriterion("create_by_ not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(Long value1, Long value2) {
            addCriterion("create_by_ between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(Long value1, Long value2) {
            addCriterion("create_by_ not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time_ is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time_ is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time_ =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time_ <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time_ >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time_ >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time_ <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time_ <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time_ in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time_ not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time_ between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time_ not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 21 17:21:52 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated Mon Aug 21 17:21:52 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}