package com.cos.model;

import java.util.Date;

import com.cos.common.utils.DateTimeUtil;

public class Entry {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.topic_id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Long topicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.form_url_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private String formUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.title_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.img_url_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.img_width_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Integer imgWidth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.img_height_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Integer imgHeight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.desc_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.sort_id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Integer sortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.grade_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Integer grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.comment_num_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Integer commentNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.remark_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.curr_version_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Short currVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.is_carousel_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Short isCarousel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.status_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.create_by_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column entry.create_time_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	private Date createTime;
	
	private String author;
		
	private String accountName;
		
	private Long cpCount;
		
	private String createTimeString;
	
	private String zoominUrl;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.id_
	 * @return  the value of entry.id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.id_
	 * @param id  the value for entry.id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.topic_id_
	 * @return  the value of entry.topic_id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Long getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.topic_id_
	 * @param topicId  the value for entry.topic_id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.form_url_
	 * @return  the value of entry.form_url_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public String getFormUrl() {
		return formUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.form_url_
	 * @param formUrl  the value for entry.form_url_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setFormUrl(String formUrl) {
		this.formUrl = formUrl == null ? null : formUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.title_
	 * @return  the value of entry.title_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.title_
	 * @param title  the value for entry.title_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.img_url_
	 * @return  the value of entry.img_url_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.img_url_
	 * @param imgUrl  the value for entry.img_url_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl == null ? null : imgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.img_width_
	 * @return  the value of entry.img_width_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Integer getImgWidth() {
		return imgWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.img_width_
	 * @param imgWidth  the value for entry.img_width_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setImgWidth(Integer imgWidth) {
		this.imgWidth = imgWidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.img_height_
	 * @return  the value of entry.img_height_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Integer getImgHeight() {
		return imgHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.img_height_
	 * @param imgHeight  the value for entry.img_height_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setImgHeight(Integer imgHeight) {
		this.imgHeight = imgHeight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.desc_
	 * @return  the value of entry.desc_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.desc_
	 * @param desc  the value for entry.desc_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.sort_id_
	 * @return  the value of entry.sort_id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Integer getSortId() {
		return sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.sort_id_
	 * @param sortId  the value for entry.sort_id_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.grade_
	 * @return  the value of entry.grade_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.grade_
	 * @param grade  the value for entry.grade_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.comment_num_
	 * @return  the value of entry.comment_num_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Integer getCommentNum() {
		return commentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.comment_num_
	 * @param commentNum  the value for entry.comment_num_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setCommentNum(Integer commentNum) {
		this.commentNum = commentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.remark_
	 * @return  the value of entry.remark_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.remark_
	 * @param remark  the value for entry.remark_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.curr_version_
	 * @return  the value of entry.curr_version_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Short getCurrVersion() {
		return currVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.curr_version_
	 * @param currVersion  the value for entry.curr_version_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setCurrVersion(Short currVersion) {
		this.currVersion = currVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.is_carousel_
	 * @return  the value of entry.is_carousel_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Short getIsCarousel() {
		return isCarousel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.is_carousel_
	 * @param isCarousel  the value for entry.is_carousel_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setIsCarousel(Short isCarousel) {
		this.isCarousel = isCarousel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.status_
	 * @return  the value of entry.status_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.status_
	 * @param status  the value for entry.status_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.create_by_
	 * @return  the value of entry.create_by_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.create_by_
	 * @param createBy  the value for entry.create_by_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column entry.create_time_
	 * @return  the value of entry.create_time_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column entry.create_time_
	 * @param createTime  the value for entry.create_time_
	 * @mbg.generated  Sun Nov 19 22:48:30 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public Long getCpCount() {
		return cpCount;
	}

	public void setCpCount(Long cpCount) {
		this.cpCount = cpCount;
	}

	public String getCreateTimeString() {
		return createTimeString;
	}

	public void setCreateTimeString(String createTimeString) {
		createTimeString=DateTimeUtil.formatDate(createTime, "yyyy-MM-dd");
		this.createTimeString = createTimeString;
	}

	public String getZoominUrl() {
		return zoominUrl;
	}

	public void setZoominUrl(String zoominUrl) {
		this.zoominUrl = zoominUrl;
	}
}