package com.cos.model;

import java.util.Date;

public class Fans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.account_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.group_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.fans_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    private Long fansId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.remark_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.create_by_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.create_time_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    private Date createTime;

    private String fansName;

    private String fansAccountName;

	private String fansDesc;

    private String name;

    private String accountName;
    
    private SysAccount account;

	private String desc;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.id_
     *
     * @return the value of fans.id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public Long getId() {
        return id;
    }

    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.id_
     *
     * @param id the value for fans.id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.account_id_
     *
     * @return the value of fans.account_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.account_id_
     *
     * @param accountId the value for fans.account_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.group_id_
     *
     * @return the value of fans.group_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.group_id_
     *
     * @param groupId the value for fans.group_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.fans_id_
     *
     * @return the value of fans.fans_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public Long getFansId() {
        return fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.fans_id_
     *
     * @param fansId the value for fans.fans_id_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public void setFansId(Long fansId) {
        this.fansId = fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.remark_
     *
     * @return the value of fans.remark_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.remark_
     *
     * @param remark the value for fans.remark_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.create_by_
     *
     * @return the value of fans.create_by_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.create_by_
     *
     * @param createBy the value for fans.create_by_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.create_time_
     *
     * @return the value of fans.create_time_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.create_time_
     *
     * @param createTime the value for fans.create_time_
     *
     * @mbg.generated Wed Aug 23 16:36:03 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public String getFansName() {
		return fansName;
	}

	public void setFansName(String fansName) {
		this.fansName = fansName;
	}

	public String getFansDesc() {
		return fansDesc;
	}

	public void setFansDesc(String fansDesc) {
		this.fansDesc = fansDesc;
	}

	public String getFansAccountName() {
		return fansAccountName;
	}

	public void setFansAccountName(String fansAccountName) {
		this.fansAccountName = fansAccountName;
	}

	public SysAccount getAccount() {
		return account;
	}

	public void setAccount(SysAccount account) {
		this.account = account;
	}
}