package com.cos.model;

import java.util.Date;

public class Grade {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.id_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.grade_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	private Integer grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.type_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	private Short type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.taget_id_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	private Long tagetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.create_by_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	private Long createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.create_time_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.id_
	 * @return  the value of grade.id_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.id_
	 * @param id  the value for grade.id_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.grade_
	 * @return  the value of grade.grade_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.grade_
	 * @param grade  the value for grade.grade_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.type_
	 * @return  the value of grade.type_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public Short getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.type_
	 * @param type  the value for grade.type_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public void setType(Short type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.taget_id_
	 * @return  the value of grade.taget_id_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public Long getTagetId() {
		return tagetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.taget_id_
	 * @param tagetId  the value for grade.taget_id_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public void setTagetId(Long tagetId) {
		this.tagetId = tagetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.create_by_
	 * @return  the value of grade.create_by_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public Long getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.create_by_
	 * @param createBy  the value for grade.create_by_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public void setCreateBy(Long createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.create_time_
	 * @return  the value of grade.create_time_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.create_time_
	 * @param createTime  the value for grade.create_time_
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}