package com.cos.model;

import java.util.Date;

public class SysEmail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_email.id_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_email.from_account_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	private Long fromAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_email.to_account_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	private Long toAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_email.message_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	private String message;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_email.status_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	private Short status;
	
	private String tocken;
	
 
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_email.create_time_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	private Date createTime;
	
	private String createTimeString;

	private SysAccount fromAccountModel;
	
	private SysAccount toAccountModel;
	
	private String fromAccountName;
	
	private String toAccountName;
	
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_email.id_
	 * @return  the value of sys_email.id_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_email.id_
	 * @param id  the value for sys_email.id_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_email.from_account_
	 * @return  the value of sys_email.from_account_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public Long getFromAccount() {
		return fromAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_email.from_account_
	 * @param fromAccount  the value for sys_email.from_account_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public void setFromAccount(Long fromAccount) {
		this.fromAccount = fromAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_email.to_account_
	 * @return  the value of sys_email.to_account_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public Long getToAccount() {
		return toAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_email.to_account_
	 * @param toAccount  the value for sys_email.to_account_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public void setToAccount(Long toAccount) {
		this.toAccount = toAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_email.message_
	 * @return  the value of sys_email.message_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_email.message_
	 * @param message  the value for sys_email.message_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public void setMessage(String message) {
		this.message = message == null ? null : message.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_email.status_
	 * @return  the value of sys_email.status_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_email.status_
	 * @param status  the value for sys_email.status_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_email.create_time_
	 * @return  the value of sys_email.create_time_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_email.create_time_
	 * @param createTime  the value for sys_email.create_time_
	 * @mbg.generated  Tue May 30 21:55:46 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateTimeString() {
		return createTimeString;
	}

	public void setCreateTimeString(String createTimeString) {
		this.createTimeString = createTimeString;
	}

	 
	public String getTocken() {
		return tocken;
	}

	public void setTocken(String tocken) {
		this.tocken = tocken;
	}

	public SysAccount getFromAccountModel() {
		return fromAccountModel;
	}

	public void setFromAccountModel(SysAccount fromAccountModel) {
		this.fromAccountModel = fromAccountModel;
	}

	public SysAccount getToAccountModel() {
		return toAccountModel;
	}

	public void setToAccountModel(SysAccount toAccountModel) {
		this.toAccountModel = toAccountModel;
	}

	public String getFromAccountName() {
		return fromAccountName;
	}

	public void setFromAccountName(String fromAccountName) {
		this.fromAccountName = fromAccountName;
	}

	public String getToAccountName() {
		return toAccountName;
	}

	public void setToAccountName(String toAccountName) {
		this.toAccountName = toAccountName;
	}
}