package com.cos.model;

import java.util.Date;

public class TopicToTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_to_tag.id_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_to_tag.tag_name_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_to_tag.topic_id_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_to_tag.create_by_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic_to_tag.create_time_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_to_tag.id_
     *
     * @return the value of topic_to_tag.id_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_to_tag.id_
     *
     * @param id the value for topic_to_tag.id_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_to_tag.tag_name_
     *
     * @return the value of topic_to_tag.tag_name_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_to_tag.tag_name_
     *
     * @param tagName the value for topic_to_tag.tag_name_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public void setTagName(String tagName) {
        this.tagName = tagName == null ? null : tagName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_to_tag.topic_id_
     *
     * @return the value of topic_to_tag.topic_id_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_to_tag.topic_id_
     *
     * @param topicId the value for topic_to_tag.topic_id_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_to_tag.create_by_
     *
     * @return the value of topic_to_tag.create_by_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_to_tag.create_by_
     *
     * @param createBy the value for topic_to_tag.create_by_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic_to_tag.create_time_
     *
     * @return the value of topic_to_tag.create_time_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic_to_tag.create_time_
     *
     * @param createTime the value for topic_to_tag.create_time_
     *
     * @mbg.generated Sun Apr 30 23:42:43 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}