package com.cos.model;

import java.util.Date;

public class ImgFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img_file.id_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img_file.url_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img_file.type_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    private String type;

	private Short currVersion;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img_file.create_by_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img_file.create_time_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img_file.id_
     *
     * @return the value of img_file.id_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img_file.id_
     *
     * @param id the value for img_file.id_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img_file.url_
     *
     * @return the value of img_file.url_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img_file.url_
     *
     * @param url the value for img_file.url_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img_file.type_
     *
     * @return the value of img_file.type_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img_file.type_
     *
     * @param type the value for img_file.type_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img_file.create_by_
     *
     * @return the value of img_file.create_by_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img_file.create_by_
     *
     * @param createBy the value for img_file.create_by_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img_file.create_time_
     *
     * @return the value of img_file.create_time_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img_file.create_time_
     *
     * @param createTime the value for img_file.create_time_
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	public Short getCurrVersion() {
		return currVersion;
	}

	public void setCurrVersion(Short currVersion) {
		this.currVersion = currVersion;
	}
}