package com.cos.model;

import java.util.Date;

public class SysAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.user_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.account_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String accountName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.nickname_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.password_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.sex_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Short sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.level_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Short level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.vip_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Short vip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.fans_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer fans;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.attention_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer attention;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.topic_count_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer topicCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.entry_count_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer entryCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.birth_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer birth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.province_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.provice_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String proviceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.city_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.city_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String cityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.area_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Integer area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.area_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.password_protect_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Short passwordProtect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.protect_answer_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String protectAnswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.school_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String school;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.major_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String major;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.work_unit_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String workUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.job_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String job;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.study_target_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Short studyTarget;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.attention_technology_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String attentionTechnology;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.email_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.img_path_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String imgPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.about_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String about;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.desc_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.hash_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String hash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.mobile_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.qq_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.weChat
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String wechat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.momo
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String momo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.type_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.start_date_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.end_date_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.relevance_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Long relevanceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.organization_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Long organizationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.post_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Long postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.islocked_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String islocked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.company_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Long companyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.status_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.tocken_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String tocken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.curr_version_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Short currVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.validatecode_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private String validatecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.created_by_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Long createdBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.created_time_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Date createdTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.last_updated_by_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Long lastUpdatedBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_account.last_updated_time_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	private Date lastUpdatedTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.id_
	 * @return  the value of sys_account.id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.id_
	 * @param id  the value for sys_account.id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.user_name_
	 * @return  the value of sys_account.user_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.user_name_
	 * @param userName  the value for sys_account.user_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.account_name_
	 * @return  the value of sys_account.account_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getAccountName() {
		return accountName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.account_name_
	 * @param accountName  the value for sys_account.account_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setAccountName(String accountName) {
		this.accountName = accountName == null ? null : accountName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.nickname_
	 * @return  the value of sys_account.nickname_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.nickname_
	 * @param nickname  the value for sys_account.nickname_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.password_
	 * @return  the value of sys_account.password_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.password_
	 * @param password  the value for sys_account.password_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.sex_
	 * @return  the value of sys_account.sex_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.sex_
	 * @param sex  the value for sys_account.sex_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.level_
	 * @return  the value of sys_account.level_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Short getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.level_
	 * @param level  the value for sys_account.level_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setLevel(Short level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.vip_
	 * @return  the value of sys_account.vip_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Short getVip() {
		return vip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.vip_
	 * @param vip  the value for sys_account.vip_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setVip(Short vip) {
		this.vip = vip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.fans_
	 * @return  the value of sys_account.fans_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getFans() {
		return fans;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.fans_
	 * @param fans  the value for sys_account.fans_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setFans(Integer fans) {
		this.fans = fans;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.attention_
	 * @return  the value of sys_account.attention_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getAttention() {
		return attention;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.attention_
	 * @param attention  the value for sys_account.attention_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setAttention(Integer attention) {
		this.attention = attention;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.topic_count_
	 * @return  the value of sys_account.topic_count_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getTopicCount() {
		return topicCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.topic_count_
	 * @param topicCount  the value for sys_account.topic_count_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setTopicCount(Integer topicCount) {
		this.topicCount = topicCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.entry_count_
	 * @return  the value of sys_account.entry_count_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getEntryCount() {
		return entryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.entry_count_
	 * @param entryCount  the value for sys_account.entry_count_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setEntryCount(Integer entryCount) {
		this.entryCount = entryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.birth_
	 * @return  the value of sys_account.birth_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getBirth() {
		return birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.birth_
	 * @param birth  the value for sys_account.birth_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setBirth(Integer birth) {
		this.birth = birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.province_
	 * @return  the value of sys_account.province_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.province_
	 * @param province  the value for sys_account.province_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setProvince(Integer province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.provice_name_
	 * @return  the value of sys_account.provice_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getProviceName() {
		return proviceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.provice_name_
	 * @param proviceName  the value for sys_account.provice_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setProviceName(String proviceName) {
		this.proviceName = proviceName == null ? null : proviceName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.city_
	 * @return  the value of sys_account.city_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.city_
	 * @param city  the value for sys_account.city_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setCity(Integer city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.city_name_
	 * @return  the value of sys_account.city_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getCityName() {
		return cityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.city_name_
	 * @param cityName  the value for sys_account.city_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setCityName(String cityName) {
		this.cityName = cityName == null ? null : cityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.area_
	 * @return  the value of sys_account.area_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Integer getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.area_
	 * @param area  the value for sys_account.area_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setArea(Integer area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.area_name_
	 * @return  the value of sys_account.area_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.area_name_
	 * @param areaName  the value for sys_account.area_name_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName == null ? null : areaName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.password_protect_
	 * @return  the value of sys_account.password_protect_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Short getPasswordProtect() {
		return passwordProtect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.password_protect_
	 * @param passwordProtect  the value for sys_account.password_protect_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setPasswordProtect(Short passwordProtect) {
		this.passwordProtect = passwordProtect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.protect_answer_
	 * @return  the value of sys_account.protect_answer_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getProtectAnswer() {
		return protectAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.protect_answer_
	 * @param protectAnswer  the value for sys_account.protect_answer_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setProtectAnswer(String protectAnswer) {
		this.protectAnswer = protectAnswer == null ? null : protectAnswer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.school_
	 * @return  the value of sys_account.school_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.school_
	 * @param school  the value for sys_account.school_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setSchool(String school) {
		this.school = school == null ? null : school.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.major_
	 * @return  the value of sys_account.major_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getMajor() {
		return major;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.major_
	 * @param major  the value for sys_account.major_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setMajor(String major) {
		this.major = major == null ? null : major.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.work_unit_
	 * @return  the value of sys_account.work_unit_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getWorkUnit() {
		return workUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.work_unit_
	 * @param workUnit  the value for sys_account.work_unit_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setWorkUnit(String workUnit) {
		this.workUnit = workUnit == null ? null : workUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.job_
	 * @return  the value of sys_account.job_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.job_
	 * @param job  the value for sys_account.job_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setJob(String job) {
		this.job = job == null ? null : job.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.study_target_
	 * @return  the value of sys_account.study_target_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Short getStudyTarget() {
		return studyTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.study_target_
	 * @param studyTarget  the value for sys_account.study_target_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setStudyTarget(Short studyTarget) {
		this.studyTarget = studyTarget;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.attention_technology_
	 * @return  the value of sys_account.attention_technology_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getAttentionTechnology() {
		return attentionTechnology;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.attention_technology_
	 * @param attentionTechnology  the value for sys_account.attention_technology_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setAttentionTechnology(String attentionTechnology) {
		this.attentionTechnology = attentionTechnology == null ? null : attentionTechnology.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.email_
	 * @return  the value of sys_account.email_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.email_
	 * @param email  the value for sys_account.email_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.img_path_
	 * @return  the value of sys_account.img_path_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.img_path_
	 * @param imgPath  the value for sys_account.img_path_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.about_
	 * @return  the value of sys_account.about_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getAbout() {
		return about;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.about_
	 * @param about  the value for sys_account.about_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setAbout(String about) {
		this.about = about == null ? null : about.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.desc_
	 * @return  the value of sys_account.desc_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.desc_
	 * @param desc  the value for sys_account.desc_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.hash_
	 * @return  the value of sys_account.hash_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getHash() {
		return hash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.hash_
	 * @param hash  the value for sys_account.hash_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setHash(String hash) {
		this.hash = hash == null ? null : hash.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.mobile_
	 * @return  the value of sys_account.mobile_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.mobile_
	 * @param mobile  the value for sys_account.mobile_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.qq_
	 * @return  the value of sys_account.qq_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.qq_
	 * @param qq  the value for sys_account.qq_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setQq(String qq) {
		this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.weChat
	 * @return  the value of sys_account.weChat
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getWechat() {
		return wechat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.weChat
	 * @param wechat  the value for sys_account.weChat
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setWechat(String wechat) {
		this.wechat = wechat == null ? null : wechat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.momo
	 * @return  the value of sys_account.momo
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getMomo() {
		return momo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.momo
	 * @param momo  the value for sys_account.momo
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setMomo(String momo) {
		this.momo = momo == null ? null : momo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.type_
	 * @return  the value of sys_account.type_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.type_
	 * @param type  the value for sys_account.type_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.start_date_
	 * @return  the value of sys_account.start_date_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.start_date_
	 * @param startDate  the value for sys_account.start_date_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.end_date_
	 * @return  the value of sys_account.end_date_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.end_date_
	 * @param endDate  the value for sys_account.end_date_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.relevance_id_
	 * @return  the value of sys_account.relevance_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Long getRelevanceId() {
		return relevanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.relevance_id_
	 * @param relevanceId  the value for sys_account.relevance_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setRelevanceId(Long relevanceId) {
		this.relevanceId = relevanceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.organization_id_
	 * @return  the value of sys_account.organization_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Long getOrganizationId() {
		return organizationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.organization_id_
	 * @param organizationId  the value for sys_account.organization_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.post_id_
	 * @return  the value of sys_account.post_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Long getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.post_id_
	 * @param postId  the value for sys_account.post_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setPostId(Long postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.islocked_
	 * @return  the value of sys_account.islocked_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getIslocked() {
		return islocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.islocked_
	 * @param islocked  the value for sys_account.islocked_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setIslocked(String islocked) {
		this.islocked = islocked == null ? null : islocked.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.company_id_
	 * @return  the value of sys_account.company_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Long getCompanyId() {
		return companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.company_id_
	 * @param companyId  the value for sys_account.company_id_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.status_
	 * @return  the value of sys_account.status_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.status_
	 * @param status  the value for sys_account.status_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.tocken_
	 * @return  the value of sys_account.tocken_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getTocken() {
		return tocken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.tocken_
	 * @param tocken  the value for sys_account.tocken_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setTocken(String tocken) {
		this.tocken = tocken == null ? null : tocken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.curr_version_
	 * @return  the value of sys_account.curr_version_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Short getCurrVersion() {
		return currVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.curr_version_
	 * @param currVersion  the value for sys_account.curr_version_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setCurrVersion(Short currVersion) {
		this.currVersion = currVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.validatecode_
	 * @return  the value of sys_account.validatecode_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public String getValidatecode() {
		return validatecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.validatecode_
	 * @param validatecode  the value for sys_account.validatecode_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setValidatecode(String validatecode) {
		this.validatecode = validatecode == null ? null : validatecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.created_by_
	 * @return  the value of sys_account.created_by_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Long getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.created_by_
	 * @param createdBy  the value for sys_account.created_by_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.created_time_
	 * @return  the value of sys_account.created_time_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Date getCreatedTime() {
		return createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.created_time_
	 * @param createdTime  the value for sys_account.created_time_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.last_updated_by_
	 * @return  the value of sys_account.last_updated_by_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Long getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.last_updated_by_
	 * @param lastUpdatedBy  the value for sys_account.last_updated_by_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setLastUpdatedBy(Long lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_account.last_updated_time_
	 * @return  the value of sys_account.last_updated_time_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public Date getLastUpdatedTime() {
		return lastUpdatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_account.last_updated_time_
	 * @param lastUpdatedTime  the value for sys_account.last_updated_time_
	 * @mbg.generated  Wed Nov 01 00:14:03 CST 2017
	 */
	public void setLastUpdatedTime(Date lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}
}