package com.cos.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.cos.model.FullIndex;
import com.cos.model.FullIndexExample;

public interface FullIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    long countByExample(FullIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int deleteByExample(FullIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int insert(FullIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int insertSelective(FullIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    List<FullIndex> selectByExample(FullIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    FullIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") FullIndex record, @Param("example") FullIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int updateByExample(@Param("record") FullIndex record, @Param("example") FullIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int updateByPrimaryKeySelective(FullIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_index
     *
     * @mbg.generated Sun Sep 10 21:35:50 CST 2017
     */
    int updateByPrimaryKey(FullIndex record);

	List<Map<String,Long>> queryTopicAndEntryByPage(@Param("word") String word,@Param("first") Integer first,@Param("limit") Integer limit);

	Long queryTopicAndEntryCount(@Param("word") String word);

	void removeStatusByTopic(@Param("topicId") Long topicId);

}