package com.cos.dao;

import com.cos.model.TopicToTag;
import com.cos.model.TopicToTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicToTagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	long countByExample(TopicToTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	int deleteByExample(TopicToTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	int insert(TopicToTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	int insertSelective(TopicToTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */List<TopicToTag> selectByExample(TopicToTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	TopicToTag selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */int updateByExampleSelective(@Param("record") TopicToTag record,@Param("example") TopicToTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */int updateByExample(@Param("record") TopicToTag record,@Param("example") TopicToTagExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	int updateByPrimaryKeySelective(TopicToTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table topic_to_tag
	 * @mbg.generated  Tue Apr 11 18:55:48 CST 2017
	 */
	int updateByPrimaryKey(TopicToTag record);
}