package com.cos.dao;

import com.cos.model.ImgFile;
import com.cos.model.ImgFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    long countByExample(ImgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int deleteByExample(ImgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int insert(ImgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int insertSelective(ImgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    List<ImgFile> selectByExample(ImgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    ImgFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") ImgFile record, @Param("example") ImgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int updateByExample(@Param("record") ImgFile record, @Param("example") ImgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int updateByPrimaryKeySelective(ImgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img_file
     *
     * @mbg.generated Sat Oct 07 15:14:02 CST 2017
     */
    int updateByPrimaryKey(ImgFile record);
}