package com.cos.dao;

import com.cos.model.ProvinceCode;
import com.cos.model.ProvinceCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvinceCodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	long countByExample(ProvinceCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	int deleteByExample(ProvinceCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	int insert(ProvinceCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	int insertSelective(ProvinceCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */List<ProvinceCode> selectByExample(ProvinceCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	ProvinceCode selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */int updateByExampleSelective(@Param("record") ProvinceCode record,@Param("example") ProvinceCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */int updateByExample(@Param("record") ProvinceCode record,@Param("example") ProvinceCodeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	int updateByPrimaryKeySelective(ProvinceCode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table province_code
	 * @mbg.generated  Tue Nov 07 16:22:34 CST 2017
	 */
	int updateByPrimaryKey(ProvinceCode record);
}