package com.cos.dao;

import com.cos.model.Topic;
import com.cos.model.TopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    long countByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int deleteByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    List<Topic> selectByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    Topic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int updateByExample(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int updateByPrimaryKeySelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Tue Mar 07 11:02:04 CST 2017
     */
    int updateByPrimaryKey(Topic record);
    
	/**
	 * 
	 * @param example
	 * @return
	 */
	List<Topic> selectPageByExample(TopicExample example);
	/**
	 * 
	 * @param example
	 * @return
	 */
	Long queryTableSortId(TopicExample example);
	/**
	 * 
	 * @param example
	 * @return
	 */
	Topic  queryNextNode(TopicExample example);
	
	List<Topic> selectAttentionTopicByPage(@Param("ids")List<Long> ids,@Param("size")int size,@Param("orderBy") String orderBy);

	List<Topic> queryTopTopic(@Param("types")List<String> types,@Param("size")int size);
}