package com.cos.dao;

import com.cos.model.Grade;
import com.cos.model.GradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GradeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	long countByExample(GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	int deleteByExample(GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	int insert(Grade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	int insertSelective(Grade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */List<Grade> selectByExample(GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	Grade selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */int updateByExampleSelective(@Param("record") Grade record,@Param("example") GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */int updateByExample(@Param("record") Grade record,@Param("example") GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	int updateByPrimaryKeySelective(Grade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbg.generated  Fri Mar 31 19:32:28 CST 2017
	 */
	int updateByPrimaryKey(Grade record);
}